version: "3"
services:
  node:
    restart: always
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - 3001:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
